import Link from "next/link";
import { getLocale } from "@/lib/i18n.server";
import { getCurrentUser } from "@/lib/session";
import { hasRole } from "@/lib/authz";
import { listDigests } from "@/lib/digest";
import { formatNumber } from "@/lib/utils";
import { generateNewDigest } from "./actions";
import "../daylight.css";
import "./digest.css";

export const dynamic = "force-dynamic";

export default async function DigestListPage() {
  const ar = getLocale() === "ar";
  const session = await getCurrentUser();
  const canGenerate = hasRole(session, "MANAGER");

  const digests = await listDigests(50);
  const dateFmt = new Intl.DateTimeFormat("en-US", { day: "numeric", month: "short", year: "numeric" });
  const relativeFmt = new Intl.DateTimeFormat("en-US", { day: "numeric", month: "short" });

  return (
    <div className="dl-page" dir={ar ? "rtl" : "ltr"}>
      <div className="br-wrap">
        <div className="br-ribbon">
          <div className="br-title-box">
            <span className="eb"><span className="tick" />{ar ? "الأفراد" : "People"}</span>
            <h1>{ar ? "الموجز" : "Digest"}</h1>
          </div>
          <div className="br-intro">
            {ar
              ? "موجز تنفيذي يولّده الدماغ عند الطلب — أهمّ ما يحتاج انتباهك في بطاقات ذكية."
              : "An executive digest generated by the brain on demand — what matters most, in smart cards."}
          </div>
        </div>

        {canGenerate ? (
          <div className="br-controls">
            <form action={generateNewDigest}>
              <button type="submit" className="br-btn br-btn-primary">
                ✦ {ar ? "ولّد موجزاً جديداً" : "Generate a new digest"}
              </button>
            </form>
          </div>
        ) : null}

        <div id="digestCards">
          <div className="br-panel">
            <h2>{ar ? "الموجزات" : "Digests"}</h2>
            <div className="sub">{ar ? "أحدث أولاً" : "Newest first"}</div>
            {digests.length === 0 ? (
              <div className="br-row" style={{ margin: 0 }}>
                <span className="br-chip info">✦</span>
                <div className="rt">
                  <div className="tt">{ar ? "لا توجد موجزات بعد" : "No digests yet"}</div>
                  <div className="ts">{ar ? "ولّد أول موجز أسبوعي." : "Generate the first weekly digest."}</div>
                </div>
              </div>
            ) : (
              <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 12 }}>
                {digests.map((d) => (
                  <Link
                    key={d.id}
                    href={`/digest/${d.id}`}
                    className="br-row"
                    style={{ margin: 0, textDecoration: "none" }}
                  >
                    <span className="br-chip info">
                      {formatNumber(d.insightCount)}
                    </span>
                    <div className="rt">
                      <div className="tt">
                        {relativeFmt.format(d.weekStart)} → {relativeFmt.format(d.weekEnd)}
                      </div>
                      <div className="ts">{d.summary}</div>
                      <div className="ts">
                        {ar ? "صدر" : "Issued"} {dateFmt.format(d.createdAt)} ·{" "}
                        {formatNumber(d.insightCount)} {ar ? "إشارة" : "signals"}
                      </div>
                    </div>
                  </Link>
                ))}
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
