-- VOAC schema — additive D1 migration.
-- Generated by scripts/build/gen-voac-d1-migration.mjs from the local dev
-- database's own sqlite_master. Do not hand-edit; regenerate instead.
--
-- ADDITIVE ONLY: four new tables, their indexes, and two nullable columns
-- on DairyBatch. No DROP, no ALTER of an existing column, no data rewrite.
-- Existing rows are untouched.
--
-- D1 has no interactive transactions, so a failure part-way leaves the
-- database half-migrated. Every statement below is IF NOT EXISTS so a
-- re-run after a partial failure is safe.

CREATE TABLE IF NOT EXISTS "AgentProposal" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "tenantId" TEXT NOT NULL,
    "runId" TEXT NOT NULL,
    "companyId" TEXT,
    "counterpartyCompanyId" TEXT,
    "title" TEXT NOT NULL,
    "rationale" TEXT NOT NULL,
    "estimatedValueJod" REAL,
    "status" TEXT NOT NULL DEFAULT 'PENDING',
    "decidedById" TEXT,
    "decidedAt" DATETIME,
    "decisionNote" TEXT,
    "realizedValueJod" REAL,
    "realizedAt" DATETIME,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "confidence" REAL,
    CONSTRAINT "AgentProposal_runId_fkey" FOREIGN KEY ("runId") REFERENCES "AgentRun" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE IF NOT EXISTS "AgentRun" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "tenantId" TEXT NOT NULL,
    "companyId" TEXT,
    "roleId" TEXT NOT NULL,
    "topology" TEXT NOT NULL,
    "objective" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'RUNNING',
    "skillVersion" TEXT NOT NULL DEFAULT 'v0',
    "llmCalls" INTEGER NOT NULL DEFAULT 0,
    "tokensIn" INTEGER NOT NULL DEFAULT 0,
    "tokensOut" INTEGER NOT NULL DEFAULT 0,
    "latencyMs" INTEGER NOT NULL DEFAULT 0,
    "error" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "endedAt" DATETIME
);
CREATE TABLE IF NOT EXISTS "AgentStep" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "tenantId" TEXT NOT NULL,
    "runId" TEXT NOT NULL,
    "parentStepId" TEXT,
    "seq" INTEGER NOT NULL DEFAULT 0,
    "roleId" TEXT NOT NULL,
    "kind" TEXT NOT NULL,
    "input" TEXT NOT NULL,
    "output" TEXT,
    "score" REAL,
    "scoredBy" TEXT,
    "tokensIn" INTEGER NOT NULL DEFAULT 0,
    "tokensOut" INTEGER NOT NULL DEFAULT 0,
    "latencyMs" INTEGER NOT NULL DEFAULT 0,
    "error" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "AgentStep_runId_fkey" FOREIGN KEY ("runId") REFERENCES "AgentRun" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE IF NOT EXISTS "VoacRoster" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "tenantId" TEXT NOT NULL,
    "companyId" TEXT NOT NULL,
    "roleIds" TEXT NOT NULL DEFAULT '',
    "dailyProposalCap" INTEGER NOT NULL DEFAULT 5,
    "cadenceHours" INTEGER NOT NULL DEFAULT 24,
    "enabled" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
);
CREATE INDEX IF NOT EXISTS "AgentProposal_companyId_idx" ON "AgentProposal"("companyId");
CREATE INDEX IF NOT EXISTS "AgentProposal_runId_idx" ON "AgentProposal"("runId");
CREATE INDEX IF NOT EXISTS "AgentProposal_tenantId_status_idx" ON "AgentProposal"("tenantId", "status");
CREATE INDEX IF NOT EXISTS "AgentRun_createdAt_idx" ON "AgentRun"("createdAt");
CREATE INDEX IF NOT EXISTS "AgentRun_status_idx" ON "AgentRun"("status");
CREATE INDEX IF NOT EXISTS "AgentRun_tenantId_companyId_idx" ON "AgentRun"("tenantId", "companyId");
CREATE INDEX IF NOT EXISTS "AgentRun_tenantId_roleId_idx" ON "AgentRun"("tenantId", "roleId");
CREATE INDEX IF NOT EXISTS "AgentStep_parentStepId_idx" ON "AgentStep"("parentStepId");
CREATE INDEX IF NOT EXISTS "AgentStep_runId_seq_idx" ON "AgentStep"("runId", "seq");
CREATE INDEX IF NOT EXISTS "AgentStep_tenantId_idx" ON "AgentStep"("tenantId");
CREATE UNIQUE INDEX IF NOT EXISTS "VoacRoster_tenantId_companyId_key" ON "VoacRoster"("tenantId", "companyId");
CREATE INDEX IF NOT EXISTS "VoacRoster_tenantId_idx" ON "VoacRoster"("tenantId");

-- Nullable on purpose: an un-entered price must stay visibly
-- un-entered, never read as zero recoverable value.
ALTER TABLE "DairyBatch" ADD COLUMN "pricePerLiter" REAL;
ALTER TABLE "DairyBatch" ADD COLUMN "costPerLiter" REAL;
